### ISSUE TITLE
erros when running algs/simulator_multi_process.py

### ISSUE THREAD

**Issue by WinnieZM** [CGCL-codes/HCB-pHCB#5]
Hello. After modifying the config file, when I run simulator_multi_process.py , the following error message will appear. How should I modify the code?

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "D:\software\Anaconda3\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "D:\GitHub_backup\HCB-pHCB\algsE\simulator_multi_process.py", line 102, in simulationPerUser
    for algname,alg in algorithms.items():
NameError: name 'algorithms' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\GitHub_backup\HCB-pHCB\algsE\simulator_multi_process.py", line 184, in <module>
    AlgReward = simiExp.run_algorithms(algorithms)
  File "D:\GitHub_backup\HCB-pHCB\algsE\simulator_multi_process.py", line 145, in run_algorithms
    tmp_reward=result.get()
  File "D:\software\Anaconda3\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
NameError: name 'algorithms' is not defined

**Comment by yusonghust** [comment]
您的来信已收到，谢谢！祝身体健康，万事如意！宋宇华中科技大学韵苑23#
